#!/bin/bash

function HOWTO () {
	cat >&2\
		<<-	USAGE
		Usage:
				use -i to specify installation iso image
				use -f to specify the name of the disk image file
				use -t to specify the tap name
				use -v to specify vnc number
		Example: ./install-base -i [cdrom.iso] -f [disk.qcow2] -t [tap0] -v [0]
			USAGE
		exit 1
}


while getopts :i:f:t:v: opt
do
	case $opt in
	i) iso=$OPTARG
	;;
	f) diskfile=$OPTARG
	;;
	t) tap=$OPTARG
	;;
	v) vnc=$OPTARG
	;;
	\?) HOWTO
	;;
	esac
done

if [[ ! -e $iso ]]; then
	echo cannot find a valid installation iso image
	exit 1
fi
tmp=$iso
if [[ ${iso%'.iso'}'.iso' != $tmp ]]; then
	echo you need to specify a valid installation iso image
	exit 1
fi
iso=$tmp

if [[ $diskfile == "" ]]; then
	echo you need to specify a valid name for the disk file
	exit 1
fi

if [[ $tap == "" ]]; then
	echo you need to specify the tap device name
	exit 1
fi

if [[ $vnc == "" ]]; then
	echo you need to specify the vnc number
	exit 1
fi

while true
do
	if [[ -e $diskfile ]]; then
		echo 'disk file exists, are you sure to proceed? (Y/N)'
		read answer
		if [[ $answer == [Yy] ]]; then
			break
		elif [[ $answer == [Nn] ]]; then
			exit 1
		fi
	else
		break
	fi
done

qemu-img create -f qcow2 $diskfile 32G
sudo qemu-system-x86_64 -smp 2\
 	-drive file=$diskfile,if=virtio\
	-enable-kvm -m 2048M\
	-net nic,model=virtio -net tap,ifname=$tap,script=no,downscript=no\
	-vnc :$vnc\
	-cdrom $iso
