#!/bin/bash

function HOWTO () {
	cat >&2\
		<<-	USAGE
		Usage:
				use -f to specify the name of the disk image file
				use -t to specify the tap name
				use -v to specify vnc number
		Example: ./run -f [disk.qcow2] -t [tap0] -v [0]
			USAGE
		exit 1
}


while getopts :f:t:v: opt
do
	case $opt in
	f) diskfile=$OPTARG
	;;
	t) tap=$OPTARG
	;;
	v) vnc=$OPTARG
	;;
	\?) HOWTO
	;;
	esac
done

if [[ $diskfile == "" ]]; then
	echo you need to specify a valid name for the disk file
	exit 1
fi

if [[ $tap == "" ]]; then
	echo you need to specify the tap device name
	exit 1
fi

if [[ $vnc == "" ]]; then
	echo you need to specify the vnc number
	exit 1
fi

sudo qemu-system-x86_64 -smp 4\
 	-drive file=$diskfile,if=virtio\
	-enable-kvm -m 4096M\
	-net nic,model=virtio\
	-net tap,ifname=$tap,script=no,downscript=no\
	-vnc :$vnc
